### ISSUE TITLE
Would `serde` support be possible?

### ISSUE THREAD

**Issue by Byron** [mcy/byteyarn#1]
Offering `serde` support by adding a `serde` feature seems to be quite common for data-type crates and it makes them more useful downstream as one can skip conversions just to gain `serde` support.

Would that be possible here as well?

----

On another note, I switched `gix-attributes` from `kstring` to `yarn`, primarily because `yarn` offers both byte-string and UTF8-string support. Even though it took a moment to understand that string-inlining is explicit, I came to like this differentiation (and control) that comes with it, and the reward was unexpected even: an important data structure that carries a lot of (hopefully inlined) strings shrunk by ~25%, and the performance of a git-attribute heavy workload increased by 2%. I will definitely look around and try to use it in more crates. 
Thank you! ([see PR](https://github.com/Byron/gitoxide/pull/1018))

**Comment by mcy** [comment]
Hi!

That's really awesome work! I'm glad my work here has provided a performance improvement.

As for serde support, I will take a pass on that. The serde author has shown themselves to be both an irresponsible programmer and a shitty person, as recorded here: https://dragon.style/@pyrex/111003848107863932. I do not want to endorse their work or support their ecosystem.

I also think `cfg`s of this type are evil, which I have been meaning to write about at some point.

However, serde does provide a way for threading custom serialization functions, so closing this request does not actually block anyone's work. Does it mean some people won't use my library? Sure, but that's not what I'm optimizing for. :)

**Comment by mcy** [comment]
I looked at your change and wanted to point out some tips (which maybe suggest documentation improvements on my end).'

Where you did

```rust
Yarn::inlined(name).unwrap_or_else(|| name.to_string().into_boxed_str().into()),
```

it is sufficient to do

```rust
Yarn::new(name).immoralize()
```

Internally, yarn makes its best effort to inline everything, because:

1. Copying two words' worth of memory is free; your libc's memcpy has special cases for this.
2. Freeing memory sooner is better, because it makes copies free.
3. It simplifies internal book-keeping and is necessary to enable certain layout optimizations.

It may be worth having a `Yarn::new_copied()` factory as a shorthand, since I've found this to be a common pattern.

**Comment by Byron** [comment]
Thanks for letting me know and for sharing the link for extra context - I hadn't read that yet and found it very interesting. Indeed I also thought for a moment what it would mean to get rid of `serde`, `thiserror`, `anyhow` and `syn` and… I had to give up :/.

But I also have hope that capable people will step up and provide alternatives eventually.

With that said, thanks a lot for your suggestions! I tried it but was surprised by the error produced by this patch:

```patch
diff --git a/gix-attributes/src/state.rs b/gix-attributes/src/state.rs
index 585e05adc..9e01d0950 100644
--- a/gix-attributes/src/state.rs
+++ b/gix-attributes/src/state.rs
@@ -49,10 +49,7 @@ impl<'a> From<ValueRef<'a>> for Value {
 
 impl From<&str> for Value {
     fn from(v: &str) -> Self {
-        Value(
-            ByteYarn::inlined(v.as_bytes())
-                .unwrap_or_else(|| ByteYarn::from_boxed_bytes(v.as_bytes().to_vec().into_boxed_slice())),
-        )
+        Value(ByteYarn::new(v.as_bytes()).immortalize())
     }
 }

```

```
51 |     fn from(v: &str) -> Self {
   |             -  - let's call the lifetime of this reference `'1`
   |             |
   |             `v` is a reference that is only valid in the associated function body
52 |         Value(ByteYarn::new(v.as_bytes()).immortalize())
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |               |
   |               `v` escapes the associated function body here
   |               argument requires that `'1` must outlive `'static`

```

It took a moment to realize that `ByteYarn = YarnBox<'static, [u8]>`. But from there it worked. I wonder if this kind of issue can be prevented by documentation as well, but am not sure.

Here is the PR with the change and some performance data: https://github.com/Byron/gitoxide/pull/1045

**Comment by mcy** [comment]
If playing the pointless benchmark game amuses you, you should consider trying 0.3, where I've changed the core of Yarn::inlined() to reduce memory traffic (by avoiding a `memcpy@plt` call). Requires a newer toolchain though (1.71).

**Comment by Byron** [comment]
Thanks for the head's up! It's unfortunate that v0.3 will be out of reach for a while as `gix` MSRV is bound `helix-editor` which is bound to `firefox` 😁.

> If playing the pointless benchmark game amuses you [..]

I doubt that this change will be measurable, but I will at least run the `hyperfine` test to assure there isn't any unforseen regression. `hyperfine` benchmarks with real-world workloads on real repositories plus occasional profiling have been very useful to me (and it's the reason I know `byteyarn` is great), but if there is anything less pointless I am all ear for sure :).

**Comment by nanoqsh** [comment]
> It may be worth having a `Yarn::new_copied()` factory as a shorthand, since I've found this to be a common pattern.

+1
I use yarn mostly this way
